# Generated by Django 4.2.11 on 2024-04-20 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mq', '0004_userprofile_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_active',
        ),
    ]
