# Generated by Django 4.2.11 on 2024-04-24 20:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mq', '0005_remove_userprofile_is_active'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('patient', 'doctor', 'booking_date', 'time_start')},
        ),
    ]
